# Generated by Django 3.2.25 on 2024-03-28 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_userprofile_default_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='default_delivery_option',
            field=models.CharField(blank=True, default='collection', max_length=10, null=True),
        ),
    ]
