# Generated by Django 3.2.25 on 2024-03-21 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20240320_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionOrder',
            fields=[
                ('order_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='checkout.order')),
                ('collection_time', models.DateTimeField()),
            ],
            bases=('checkout.order',),
        ),
        migrations.CreateModel(
            name='DeliveryOrder',
            fields=[
                ('order_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='checkout.order')),
                ('delivery_address', models.CharField(max_length=255)),
            ],
            bases=('checkout.order',),
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_option',
        ),
    ]
