# Generated by Django 3.2.25 on 2024-03-21 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_order_delivery_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionorder',
            name='collection_time',
            field=models.DateTimeField(null=True),
        ),
    ]
