# Generated by Django 3.2.25 on 2024-03-24 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_alter_collectionorder_collection_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryorder',
            name='order_ptr',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Card'), ('cash', 'Cash')], default='Cash', max_length=10),
        ),
        migrations.DeleteModel(
            name='CollectionOrder',
        ),
        migrations.DeleteModel(
            name='DeliveryOrder',
        ),
    ]
