# Generated by Django 3.2.25 on 2024-04-01 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0010_order_user_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='delivery_cost',
            new_name='delivery',
        ),
    ]
